#The new config for Multiprefix, please follow the instructions exactly
#The first indented part after the "groups:" section is the name of teh group, it must match the EXACT name of the group in the permissions plugin
#The next one is the prefix of the group, color codes are supported, just make sure you put '' surrounding it. 
#The suffix is optional and only one suffix would be supported unless there are more requests to add multisuffix support, Color codes supported
#The chat-format section is required and the following is the variables that you can use
#       %displayname% - The prefix(es), main username, and suffix set by this plugin alone. If requested, I can add more support for other specific plugins
#       %message% - The chat message
#    Color codes supported for chat formatting
#The priority is what determins what chat formatting is used (The lowest one) and the order of the prefixes from lowest to highest
#  NOTE about PRIORITY: Due to how java handles numbers, please have unique priority numbers per group, so no duplicates, otherwise the prefix might not display

#If you would like the chat format to be optional, submit a ticket on the BukkitDev page and I will add an option to disable it. 
#Anything else, bug, suggestion or comment, please submit a ticket on the repository (Found on the BukkitDev page)

#Set this to false to use another chat-formatting plugin, The displayname will still be set to have the multiple prefixes
#Incomplete, but config setting here for future reference
chat-formatting: true

#Set this to false to use the prefix from the Permissions Plugin instead of the ones here
#Incomplete, but config setting here for future reference
prefixes: true

#Set this to true to use Essentials Nicknames instead of the normal player name
#You must change the add-prefix-suffix setting in your Essentials config.yml to false to prevent duplicate prefixes
#   If you do not do this, MultiPrefix will default to using the chat formats of the groups in this config file
#Incomplete, but config setting here for future reference
using-essentials: false

groups:
  Default:
    prefix: '&8[&fMember&8] '
    suffix: ''
    chat-format: '%displayname% &7> &f%message%'
    priority: 3
  VIP:
    prefix: '&8[&bVIP&8] '
    suffix: ''
    chat-format: '%displayname% %suffix% &7> &f%message%'
    priority: 2
  Helper:
    prefix: '&8[&aHelper&8] '
    suffix: ''
    chat-format: '%displayname% %suffix% &7> &a%message%'
    priority: 1
  Moderator:
    prefix: '&8[&dModerator&8] '
    suffix: ''
    chat-format: '%displayname% %suffix% &7> &d%message%'
    priority: 0