name: MultiPrefix
version: 2.1.1
description: Allows multiple prefixes based on groups
author: Firestar311
main: com.firestar311.multiprefix.MultiPrefix
depend: [Vault]
commands:
    multiprefix: 
        description: Reloads the config
        usage: /<command> reload